#!/bin/bash

#PBS -lwalltime=00:30:00
#PBS -lselect=1:ncpus=1:mem=2gb
#PBS -j oe
#PBS -o hpc/run_eo_0.txt

# load module
#module load anaconda3/personal

cd /rds/general/user/jp2923/home/irp-jp2923/data/abide_ii

echo "Current directory:"
pwd
echo "Contents of current directory:"
ls -l

echo "============================================================================================================================================================================================================================"

echo "------------1-------------"

source ~/.bashrc

echo "-------------2------------"

rm -r ABIDE*
rm -r FreeSurfer

echo "------------3-------------"

cp -r keep/* ./
